Warn if try to summarize variable greater than 1d
Trying to summarize a variable with greater than one dimension results
in an error (trace.py 121):

  TypeError: type numpy.ndarray doesn't define __round__ method

With these changes, variables above 1 dimension are skipped and a
warning is given.